
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";

// Comprehensive realistic truck data for different categories
const truckSeedData = [
  // Heavy-duty trucks (30 entries)
  {
    brand: "Volvo",
    model: "FH16 750",
    year: 2023,
    mileage: 12500,
    price: 185000,
    condition: "new",
    engine: "Volvo D16K 750",
    transmission: "I-Shift",
    description: "The Volvo FH16 750 is our most powerful truck, designed for the most demanding operations and heaviest transports. Features a 750 hp engine with 3550 Nm of torque, I-Shift transmission with crawler gears, and Volvo Dynamic Steering for precise handling.",
    horsepower: 750,
    features: ["GPS Navigation", "Driver Alert Support", "Lane Keeping Aid", "Adaptive Cruise Control", "Premium Sound System", "Leather Interior", "Refrigerator"],
    images: ["https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Scania",
    model: "R730 V8",
    year: 2024,
    mileage: 5800,
    price: 198500,
    condition: "new",
    engine: "Scania V8",
    transmission: "Opticruise",
    description: "The Scania R730 V8 is a flagship model with a powerful V8 engine delivering 730 hp and 3500 Nm of torque. Features Scania Opticruise transmission, retarder, and advanced driver support systems for optimal performance and safety.",
    horsepower: 730,
    features: ["Premium Connectivity", "Advanced Safety Package", "V8 Premium Sound", "Leather Interior", "Dual Refrigerators", "Microwave", "Coffee Machine"],
    images: ["https://images.unsplash.com/photo-1592839843682-f5865509bdf8?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Mercedes-Benz",
    model: "Actros 2653",
    year: 2023,
    mileage: 18200,
    price: 178000,
    condition: "used",
    engine: "OM 473",
    transmission: "PowerShift 3",
    description: "The Mercedes-Benz Actros 2653 is designed for long-haul transport with its 530 hp engine and PowerShift 3 automated transmission. Features MirrorCam instead of conventional mirrors, Predictive Powertrain Control, and Active Brake Assist 5.",
    horsepower: 530,
    features: ["MirrorCam", "Multimedia Cockpit", "Predictive Powertrain Control", "Active Brake Assist 5", "Proximity Control", "Attention Assist", "LED Headlights"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1601312378427-822b2b41da35?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "MAN",
    model: "TGX 18.640",
    year: 2022,
    mileage: 42500,
    price: 159000,
    condition: "used",
    engine: "D3876",
    transmission: "automated-manual",
    description: "The MAN TGX 18.640 is equipped with a 640 hp D3876 engine and automated manual transmission, delivering impressive power and efficiency for heavy transport. Features include a digital cockpit, advanced driver assistance systems, and comfortable living area.",
    horsepower: 640,
    features: ["Digital Cockpit", "EfficientCruise", "Lane Return Assist", "Turn Assist", "12.3-inch Display", "LED Headlights", "Long Haul Package"],
    images: ["https://images.unsplash.com/photo-1595758228881-53eca2114ba7?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1626676708484-402819bd986e?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Kenworth",
    model: "W990",
    year: 2023,
    mileage: 24800,
    price: 189000,
    condition: "certified",
    engine: "PACCAR MX-13",
    transmission: "automated-manual",
    description: "The Kenworth W990 features a PACCAR MX-13 engine with 510 hp and automated manual transmission. With its classic long-hood design, premium interior, and advanced technology, it offers both style and performance for long-haul operations.",
    horsepower: 510,
    features: ["12.9L PACCAR MX-13 Engine", "76-inch Sleeper", "Premium Interior", "Driver Performance Center", "Digital Dash Display", "Predictive Cruise Control", "Advanced Connectivity"],
    images: ["https://images.unsplash.com/photo-1600661653561-629509216228?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1601581875039-e899893d520c?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Peterbilt",
    model: "579",
    year: 2024,
    mileage: 8900,
    price: 195000,
    condition: "new",
    engine: "PACCAR MX-13",
    transmission: "automated-manual",
    description: "The Peterbilt 579 combines aerodynamic efficiency with classic styling. Featuring PACCAR MX-13 engine with 500 hp, automated manual transmission, and advanced SmartNav technology for optimal fuel efficiency and driver comfort.",
    horsepower: 500,
    features: ["SmartNav Technology", "EPIQ Dashboard", "SmartAir 2", "Bendix Wingman Fusion", "Diamond VIT Interior", "LED Lighting Package", "Air Suspension"],
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "DAF",
    model: "XF 530",
    year: 2022,
    mileage: 35600,
    price: 165000,
    condition: "certified",
    engine: "PACCAR MX-13",
    transmission: "TraXon",
    description: "The DAF XF 530 delivers exceptional fuel efficiency and driver comfort with its PACCAR MX-13 engine and TraXon automated transmission. Features advanced safety systems and spacious SuperSpace Cab for long-haul operations.",
    horsepower: 530,
    features: ["Predictive Cruise Control", "Lane Departure Warning", "Forward Collision Warning", "SuperSpace Cab", "Multimedia System", "Automatic Climate Control", "Xenon Headlights"],
    images: ["https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Iveco",
    model: "S-Way 570",
    year: 2023,
    mileage: 19800,
    price: 172000,
    condition: "used",
    engine: "Cursor 13",
    transmission: "Hi-Tronix",
    description: "The Iveco S-Way 570 features a Cursor 13 engine with 570 hp and Hi-Tronix automated transmission. Designed for maximum fuel efficiency and driver comfort with innovative cab design and advanced connectivity features.",
    horsepower: 570,
    features: ["ADAS Advanced Safety", "Connected Services", "Hi-Comfort Suspension", "Automatic Climate Control", "Infotainment System", "LED DRL", "Ergonomic Dashboard"],
    images: ["https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Mack",
    model: "Anthem 505",
    year: 2021,
    mileage: 68500,
    price: 142000,
    condition: "used",
    engine: "Mack MP8",
    transmission: "mDRIVE HD",
    description: "The Mack Anthem 505 is built for the long haul with its reliable MP8 engine and mDRIVE HD automated transmission. Features aerodynamic design, spacious interior, and Mack's legendary durability for demanding applications.",
    horsepower: 505,
    features: ["Bendix Wingman Fusion", "mDRIVE HD Transmission", "Command Steer", "Mack Connect", "LED Headlights", "Air Suspension", "Premium Interior"],
    images: ["https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Western Star",
    model: "5700XE",
    year: 2024,
    mileage: 3200,
    price: 187000,
    condition: "new",
    engine: "Detroit DD15",
    transmission: "DT12",
    description: "The Western Star 5700XE combines aerodynamic efficiency with rugged styling. Features Detroit DD15 engine with 525 hp, DT12 automated transmission, and advanced safety technologies for superior performance and fuel economy.",
    horsepower: 525,
    features: ["Detroit Assurance 5.0", "Virtual Technician", "Intelligent Powertrain Management", "Premium LED Lighting", "Air Suspension", "Ergonomic Interior", "Advanced Telematics"],
    images: ["https://images.unsplash.com/photo-1626676708484-402819bd986e?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1595758228881-53eca2114ba7?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  // Additional 20 heavy-duty trucks
  {
    brand: "Volvo",
    model: "FH13 460",
    year: 2023,
    mileage: 28500,
    price: 162000,
    condition: "certified",
    engine: "Volvo D13K",
    transmission: "I-Shift",
    description: "The Volvo FH13 460 combines efficiency and performance with a 460 hp engine and I-Shift transmission. Features enhanced safety systems, comfortable sleeper cab, and excellent fuel economy for regional and long-haul operations.",
    horsepower: 460,
    features: ["I-Shift Automated Transmission", "Enhanced Stability Program", "Driver Alert Support", "Volvo Connect", "Premium Interior", "LED Lighting", "Air Suspension"],
    images: ["https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Scania",
    model: "R500 Streamline",
    year: 2022,
    mileage: 45200,
    price: 148000,
    condition: "used",
    engine: "DC13",
    transmission: "Opticruise",
    description: "The Scania R500 Streamline offers excellent aerodynamics and fuel efficiency with its DC13 engine and Opticruise transmission. Features advanced driver assistance, comfortable interior, and superior reliability for demanding applications.",
    horsepower: 500,
    features: ["Opticruise Automated Transmission", "Streamline Aerodynamics", "Advanced Driver Support", "Scania Connect", "Comfort Suspension", "Premium Audio", "LED Headlights"],
    images: ["https://images.unsplash.com/photo-1592839843682-f5865509bdf8?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Mercedes-Benz",
    model: "Arocs 2658",
    year: 2024,
    mileage: 12800,
    price: 189000,
    condition: "new",
    engine: "OM 473",
    transmission: "PowerShift 3",
    description: "The Mercedes-Benz Arocs 2658 is designed for construction and heavy-duty applications with its robust OM 473 engine delivering 580 hp. Features advanced off-road capabilities, reinforced chassis, and comprehensive safety systems.",
    horsepower: 580,
    features: ["Off-Road Package", "Reinforced Chassis", "Active Brake Assist", "Stability Control", "Heavy-Duty Suspension", "Multimedia Cockpit", "All-Wheel Drive"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1601312378427-822b2b41da35?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "MAN",
    model: "TGS 35.460",
    year: 2023,
    mileage: 22600,
    price: 168000,
    condition: "certified",
    engine: "D2676",
    transmission: "TipMatic",
    description: "The MAN TGS 35.460 is engineered for construction and distribution with a reliable D2676 engine and TipMatic transmission. Features robust construction, excellent maneuverability, and advanced safety technologies.",
    horsepower: 460,
    features: ["TipMatic Automated Transmission", "Construction Package", "EfficientLine", "Attention Guard", "Emergency Brake Assist", "Lane Change Support", "Digital Cockpit"],
    images: ["https://images.unsplash.com/photo-1595758228881-53eca2114ba7?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1626676708484-402819bd986e?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Kenworth",
    model: "T680",
    year: 2024,
    mileage: 15400,
    price: 178000,
    condition: "new",
    engine: "PACCAR MX-13",
    transmission: "automated-manual",
    description: "The Kenworth T680 offers aerodynamic excellence and fuel efficiency with PACCAR MX-13 power and automated transmission. Features advanced driver assistance, premium comfort, and cutting-edge connectivity for modern logistics.",
    horsepower: 455,
    features: ["PACCAR MX-13 Engine", "Aerodynamic Design", "Predictive Cruise Control", "Collision Mitigation", "Premium Interior", "Digital Display", "Advanced Connectivity"],
    images: ["https://images.unsplash.com/photo-1600661653561-629509216228?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1601581875039-e899893d520c?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Peterbilt",
    model: "389",
    year: 2023,
    mileage: 38900,
    price: 165000,
    condition: "used",
    engine: "Caterpillar C15",
    transmission: "manual",
    description: "The Peterbilt 389 combines classic styling with modern performance. Features Caterpillar C15 engine with 550 hp, manual transmission, and iconic design elements that make it a favorite among owner-operators.",
    horsepower: 550,
    features: ["Classic Long Hood Design", "Chrome Package", "Premium Interior", "Performance Engine", "Heavy-Duty Suspension", "Custom Paint Options", "LED Lighting"],
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "DAF",
    model: "CF 480",
    year: 2022,
    mileage: 41800,
    price: 152000,
    condition: "used",
    engine: "PACCAR MX-11",
    transmission: "TraXon",
    description: "The DAF CF 480 provides reliable performance for distribution and regional transport with its PACCAR MX-11 engine and TraXon transmission. Features excellent fuel efficiency, driver comfort, and proven durability.",
    horsepower: 480,
    features: ["PACCAR MX-11 Engine", "TraXon Automated Transmission", "Predictive Cruise Control", "Lane Departure Warning", "Comfortable Cab", "Multimedia System", "LED Lighting"],
    images: ["https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Iveco",
    model: "Stralis XP 570",
    year: 2021,
    mileage: 58600,
    price: 138000,
    condition: "used",
    engine: "Cursor 13",
    transmission: "Hi-Tronix",
    description: "The Iveco Stralis XP 570 delivers powerful performance with its Cursor 13 engine and Hi-Tronix transmission. Features advanced driver assistance systems, comfortable interior, and excellent fuel efficiency for long-haul operations.",
    horsepower: 570,
    features: ["Cursor 13 Engine", "Hi-Tronix Automated Transmission", "Advanced Safety Package", "Driver Attention Support", "Comfort Suspension", "Connectivity Systems", "LED Lighting"],
    images: ["https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Mack",
    model: "Granite 64R",
    year: 2024,
    mileage: 8500,
    price: 175000,
    condition: "new",
    engine: "Mack MP8",
    transmission: "mDRIVE",
    description: "The Mack Granite 64R is built for severe-duty applications with its rugged MP8 engine and mDRIVE transmission. Features reinforced frame, heavy-duty components, and advanced safety systems for construction and mining operations.",
    horsepower: 505,
    features: ["MP8 Heavy-Duty Engine", "mDRIVE Transmission", "Reinforced Frame", "Heavy-Duty Suspension", "Advanced Safety Systems", "Rugged Design", "All-Weather Capability"],
    images: ["https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Western Star",
    model: "4900",
    year: 2023,
    mileage: 31200,
    price: 158000,
    condition: "certified",
    engine: "Detroit DD13",
    transmission: "manual",
    description: "The Western Star 4900 combines traditional styling with modern reliability. Features Detroit DD13 engine with 470 hp, manual transmission, and rugged construction for demanding work environments and long-haul applications.",
    horsepower: 470,
    features: ["Detroit DD13 Engine", "Traditional Styling", "Rugged Construction", "Heavy-Duty Components", "Comfortable Interior", "Reliable Performance", "Proven Durability"],
    images: ["https://images.unsplash.com/photo-1626676708484-402819bd986e?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1595758228881-53eca2114ba7?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Volvo",
    model: "VNL 860",
    year: 2024,
    mileage: 6800,
    price: 192000,
    condition: "new",
    engine: "Volvo D13TC",
    transmission: "I-Shift",
    description: "The Volvo VNL 860 offers premium long-haul comfort with its advanced D13TC engine and I-Shift transmission. Features spacious 77-inch sleeper, advanced safety systems, and exceptional fuel efficiency for professional drivers.",
    horsepower: 500,
    features: ["77-inch Sleeper", "Volvo D13TC Engine", "I-Shift Transmission", "Advanced Safety Suite", "Premium Interior", "Fuel Efficiency Package", "Driver Alert Systems"],
    images: ["https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Scania",
    model: "G450",
    year: 2022,
    mileage: 39800,
    price: 155000,
    condition: "used",
    engine: "DC13",
    transmission: "Opticruise",
    description: "The Scania G450 provides excellent performance and fuel economy with its DC13 engine and Opticruise transmission. Features robust construction, driver comfort, and proven reliability for distribution and construction applications.",
    horsepower: 450,
    features: ["DC13 Engine", "Opticruise Transmission", "Robust Construction", "Driver Comfort", "Fuel Economy", "Safety Systems", "Reliable Performance"],
    images: ["https://images.unsplash.com/photo-1592839843682-f5865509bdf8?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Mercedes-Benz",
    model: "Actros 1845",
    year: 2023,
    mileage: 26500,
    price: 169000,
    condition: "certified",
    engine: "OM 471",
    transmission: "PowerShift 3",
    description: "The Mercedes-Benz Actros 1845 delivers efficient performance with its OM 471 engine and PowerShift 3 transmission. Features MirrorCam technology, predictive powertrain control, and advanced safety systems for modern logistics.",
    horsepower: 450,
    features: ["MirrorCam Technology", "OM 471 Engine", "PowerShift 3", "Predictive Powertrain Control", "Active Safety Systems", "Multimedia Cockpit", "Efficient Design"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1601312378427-822b2b41da35?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "MAN",
    model: "TGX 26.560",
    year: 2024,
    mileage: 11200,
    price: 184000,
    condition: "new",
    engine: "D2676",
    transmission: "TipMatic",
    description: "The MAN TGX 26.560 offers exceptional power and efficiency with its D2676 engine delivering 560 hp and TipMatic transmission. Features digital cockpit, advanced driver assistance, and premium comfort for demanding transport operations.",
    horsepower: 560,
    features: ["D2676 High-Power Engine", "TipMatic Transmission", "Digital Cockpit", "Advanced Driver Assistance", "Premium Comfort", "EfficientLine Package", "Safety Technologies"],
    images: ["https://images.unsplash.com/photo-1595758228881-53eca2114ba7?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1626676708484-402819bd986e?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Kenworth",
    model: "T800",
    year: 2022,
    mileage: 48500,
    price: 145000,
    condition: "used",
    engine: "Caterpillar C15",
    transmission: "manual",
    description: "The Kenworth T800 is built for heavy-duty vocational applications with its powerful Caterpillar C15 engine and robust manual transmission. Features set-back axle configuration, reinforced frame, and proven durability for severe-duty work.",
    horsepower: 550,
    features: ["Caterpillar C15 Engine", "Heavy-Duty Manual Transmission", "Set-Back Axle", "Reinforced Frame", "Vocational Design", "Proven Durability", "Severe-Duty Capability"],
    images: ["https://images.unsplash.com/photo-1600661653561-629509216228?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1601581875039-e899893d520c?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Peterbilt",
    model: "567",
    year: 2023,
    mileage: 21800,
    price: 172000,
    condition: "certified",
    engine: "PACCAR MX-13",
    transmission: "automated-manual",
    description: "The Peterbilt 567 combines vocational capability with on-highway efficiency. Features PACCAR MX-13 engine, automated transmission, and versatile configuration options for construction, logging, and specialized transport applications.",
    horsepower: 510,
    features: ["PACCAR MX-13 Engine", "Automated Manual Transmission", "Vocational Capability", "Versatile Configuration", "Advanced Safety", "Digital Display", "Professional Interior"],
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "DAF",
    model: "XG+ 530",
    year: 2024,
    mileage: 9500,
    price: 186000,
    condition: "new",
    engine: "PACCAR MX-13",
    transmission: "TraXon",
    description: "The DAF XG+ 530 represents the pinnacle of long-haul transport with its advanced PACCAR MX-13 engine and TraXon transmission. Features premium XG+ cab, advanced connectivity, and exceptional driver comfort for professional logistics.",
    horsepower: 530,
    features: ["XG+ Premium Cab", "PACCAR MX-13 Engine", "TraXon Transmission", "Advanced Connectivity", "Premium Comfort", "Safety Technologies", "Fuel Efficiency"],
    images: ["https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Iveco",
    model: "X-Way 460",
    year: 2023,
    mileage: 18900,
    price: 158000,
    condition: "used",
    engine: "Cursor 9",
    transmission: "Hi-Tronix",
    description: "The Iveco X-Way 460 is designed for off-road and construction applications with its robust Cursor 9 engine and Hi-Tronix transmission. Features reinforced chassis, all-terrain capability, and advanced safety systems for challenging environments.",
    horsepower: 460,
    features: ["Cursor 9 Engine", "Hi-Tronix Transmission", "Off-Road Capability", "Reinforced Chassis", "All-Terrain Design", "Safety Systems", "Rugged Construction"],
    images: ["https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Mack",
    model: "Pinnacle 64T",
    year: 2024,
    mileage: 7200,
    price: 179000,
    condition: "new",
    engine: "Mack MP8",
    transmission: "mDRIVE HD",
    description: "The Mack Pinnacle 64T delivers highway efficiency and driver comfort with its refined MP8 engine and mDRIVE HD transmission. Features aerodynamic design, premium interior, and advanced technologies for long-haul excellence.",
    horsepower: 505,
    features: ["MP8 Refined Engine", "mDRIVE HD Transmission", "Aerodynamic Design", "Premium Interior", "Highway Efficiency", "Advanced Technologies", "Driver Comfort"],
    images: ["https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },
  {
    brand: "Western Star",
    model: "6900XD",
    year: 2022,
    mileage: 42800,
    price: 148000,
    condition: "used",
    engine: "Detroit DD16",
    transmission: "DT12",
    description: "The Western Star 6900XD is built for extreme-duty applications with its powerful Detroit DD16 engine and DT12 transmission. Features ultra-high-strength steel frame, heavy-duty components, and superior durability for mining and construction.",
    horsepower: 600,
    features: ["Detroit DD16 Engine", "Ultra-High-Strength Frame", "Extreme-Duty Design", "Heavy-Duty Components", "Superior Durability", "Mining Package", "Construction Ready"],
    images: ["https://images.unsplash.com/photo-1626676708484-402819bd986e?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1595758228881-53eca2114ba7?w=800&h=500&fit=crop"],
    category: "heavy-duty"
  },

  // Medium-duty trucks (30 entries)
  {
    brand: "Freightliner",
    model: "M2 106",
    year: 2024,
    mileage: 3200,
    price: 125000,
    condition: "new",
    engine: "Cummins B6.7",
    transmission: "Allison Automatic",
    description: "The Freightliner M2 106 is a versatile medium-duty truck powered by a Cummins B6.7 engine with 300 hp and Allison automatic transmission. Offers excellent visibility, maneuverability, and comfort for regional and urban delivery operations.",
    horsepower: 300,
    features: ["360° Visibility", "SmartPlex Electrical System", "Ergonomic Dashboard", "Bluetooth Connectivity", "Air Suspension Seats", "Collision Mitigation", "LED Lighting"],
    images: ["https://images.unsplash.com/photo-1591768793355-74d04bb6608f?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1532976789241-e31cc4c7c16c?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Isuzu",
    model: "FTR",
    year: 2023,
    mileage: 8700,
    price: 98500,
    condition: "used",
    engine: "Isuzu 5.2L",
    transmission: "automatic",
    description: "The Isuzu FTR is powered by a 5.2L turbocharged engine with 215 hp and Allison automatic transmission. Features a tight turning radius, spacious cab, and excellent visibility, making it ideal for urban delivery and regional distribution.",
    horsepower: 215,
    features: ["Hill Start Aid", "Tight Turning Radius", "Low-Cab Forward Design", "6-Speed Automatic", "Heated Mirrors", "Entry/Exit Grab Handles", "Air Suspension Driver's Seat"],
    images: ["https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d99?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Hino",
    model: "268A",
    year: 2022,
    mileage: 28500,
    price: 88000,
    condition: "certified",
    engine: "Hino J08E-VB",
    transmission: "automatic",
    description: "The Hino 268A is equipped with a J08E-VB engine delivering 230 hp and automatic transmission. Offers excellent fuel efficiency, driver comfort, and a comprehensive standard safety package for distribution and delivery applications.",
    horsepower: 230,
    features: ["Collision Mitigation System", "Lane Departure Warning", "Electronic Stability Control", "Bluetooth Hands-Free", "Driver's Airbag", "Air Conditioning", "Cruise Control"],
    images: ["https://images.unsplash.com/photo-1586368555537-a8be1231d20f?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Ford",
    model: "F-650",
    year: 2024,
    mileage: 1200,
    price: 115000,
    condition: "new",
    engine: "Power Stroke V8",
    transmission: "TorqShift HD",
    description: "The Ford F-650 features a 6.7L Power Stroke V8 diesel engine with 330 hp and TorqShift HD automatic transmission. Offers exceptional capability and versatility for a wide range of commercial applications and body upfits.",
    horsepower: 330,
    features: ["Tow/Haul Mode", "Upfitter Switches", "Power Equipment Group", "Air Conditioning", "Tilt/Telescoping Steering Column", "Auxiliary Audio Input", "110V Power Outlet"],
    images: ["https://images.unsplash.com/photo-1522763866081-5be09778cd8b?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Mitsubishi",
    model: "Fuso FE160",
    year: 2023,
    mileage: 15800,
    price: 85000,
    condition: "used",
    engine: "4P10 Turbodiesel",
    transmission: "Duonic 2.0",
    description: "The Mitsubishi Fuso FE160 is powered by a 4P10 turbodiesel engine with 161 hp and Duonic 2.0 dual-clutch automated manual transmission. Features excellent fuel efficiency, maneuverability, and payload capacity for urban delivery operations.",
    horsepower: 161,
    features: ["Duonic 2.0 Dual-Clutch Transmission", "ECO Mode", "Bluetooth Radio", "LED Headlamps", "Cruise Control", "Keyless Entry", "Driver's Suspension Seat"],
    images: ["https://images.unsplash.com/photo-1562876614-b8113b9aae14?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1565776877935-72d7a6dc421a?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "International",
    model: "MV607",
    year: 2024,
    mileage: 2800,
    price: 108000,
    condition: "new",
    engine: "Cummins B6.7",
    transmission: "Allison 2500",
    description: "The International MV607 combines proven Cummins B6.7 power with Allison automatic transmission for reliable medium-duty performance. Features advanced safety systems, comfortable cab design, and excellent fuel economy for delivery applications.",
    horsepower: 285,
    features: ["Electronic Stability Control", "Anti-Lock Braking System", "Traction Control", "Cruise Control", "Air Conditioning", "Power Steering", "Bluetooth Connectivity"],
    images: ["https://images.unsplash.com/photo-1601312378427-822b2b41da35?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1586368555537-a8be1231d20f?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Volvo",
    model: "VNM 300",
    year: 2023,
    mileage: 12600,
    price: 118000,
    condition: "certified",
    engine: "Volvo D8K",
    transmission: "I-Shift",
    description: "The Volvo VNM 300 delivers European engineering excellence with the D8K engine and I-Shift automated transmission. Features advanced safety systems, exceptional fuel efficiency, and driver-centric design for medium-duty applications.",
    horsepower: 300,
    features: ["I-Shift Automated Manual", "Enhanced Stability Program", "Driver Alert Support", "Lane Keeping Aid", "Volvo Connect", "LED Lighting", "Ergonomic Interior"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Kenworth",
    model: "T370",
    year: 2022,
    mileage: 34200,
    price: 95000,
    condition: "used",
    engine: "PACCAR PX-7",
    transmission: "Allison 3000",
    description: "The Kenworth T370 features a PACCAR PX-7 engine with 325 hp and Allison 3000 automatic transmission. Built for versatility and durability with premium interior appointments and advanced safety features for demanding work environments.",
    horsepower: 325,
    features: ["PACCAR PX-7 Engine", "Allison 3000 Transmission", "Air Suspension", "Premium Interior", "Advanced Safety Package", "Electronic Controls", "Ergonomic Design"],
    images: ["https://images.unsplash.com/photo-1600661653561-629509216228?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Peterbilt",
    model: "220",
    year: 2024,
    mileage: 4500,
    price: 112000,
    condition: "new",
    engine: "PACCAR PX-7",
    transmission: "Allison 2500",
    description: "The Peterbilt 220 combines classic styling with modern efficiency. Features PACCAR PX-7 engine, Allison automatic transmission, and premium amenities designed for driver comfort and operational efficiency in medium-duty applications.",
    horsepower: 300,
    features: ["SmartNav Technology", "Premium Interior", "Air Suspension Seats", "Advanced Safety Systems", "LED Lighting Package", "Bluetooth Connectivity", "Ergonomic Controls"],
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Mercedes-Benz",
    model: "Atego 1218",
    year: 2023,
    mileage: 16900,
    price: 102000,
    condition: "used",
    engine: "OM 934",
    transmission: "G85-6",
    description: "The Mercedes-Benz Atego 1218 features the reliable OM 934 engine with 175 hp and manual transmission. Known for exceptional build quality, fuel efficiency, and versatility for urban distribution and regional transport applications.",
    horsepower: 175,
    features: ["Active Brake Assist", "Attention Assist", "Electronic Stability Program", "Comfort Suspension", "Multimedia System", "Air Conditioning", "Ergonomic Workplace"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d99?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  // Additional 20 medium-duty trucks
  {
    brand: "Freightliner",
    model: "Business Class M2 112",
    year: 2023,
    mileage: 18500,
    price: 118000,
    condition: "certified",
    engine: "Cummins ISL9",
    transmission: "Allison 3000",
    description: "The Freightliner Business Class M2 112 features a Cummins ISL9 engine with 350 hp and Allison 3000 transmission. Designed for versatility and efficiency with excellent visibility, comfort features, and proven reliability for commercial applications.",
    horsepower: 350,
    features: ["Cummins ISL9 Engine", "Allison 3000 Transmission", "SmartPlex Electrical", "Advanced Safety", "Comfortable Cab", "LED Lighting", "Air Suspension Seats"],
    images: ["https://images.unsplash.com/photo-1591768793355-74d04bb6608f?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1532976789241-e31cc4c7c16c?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Isuzu",
    model: "FVR",
    year: 2024,
    mileage: 5200,
    price: 128000,
    condition: "new",
    engine: "Isuzu 6HK1-TC",
    transmission: "automatic",
    description: "The Isuzu FVR delivers robust performance with its 6HK1-TC turbocharged engine and automatic transmission. Features increased payload capacity, enhanced safety systems, and superior maneuverability for medium-duty commercial applications.",
    horsepower: 260,
    features: ["6HK1-TC Turbocharged Engine", "Increased Payload", "Enhanced Safety", "Superior Maneuverability", "Comfort Features", "Fuel Efficiency", "Reliability Package"],
    images: ["https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d99?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Hino",
    model: "338",
    year: 2023,
    mileage: 22800,
    price: 95000,
    condition: "used",
    engine: "Hino J08E-VD",
    transmission: "automatic",
    description: "The Hino 338 provides dependable performance with its J08E-VD engine and automatic transmission. Features enhanced safety systems, comfortable cab design, and excellent fuel economy for distribution and delivery operations.",
    horsepower: 260,
    features: ["J08E-VD Engine", "Enhanced Safety Systems", "Comfortable Cab", "Fuel Economy", "Distribution Ready", "Delivery Optimized", "Reliable Performance"],
    images: ["https://images.unsplash.com/photo-1586368555537-a8be1231d20f?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Ford",
    model: "F-750",
    year: 2024,
    mileage: 3800,
    price: 135000,
    condition: "new",
    engine: "Power Stroke V8",
    transmission: "TorqShift HD",
    description: "The Ford F-750 offers superior capability with its Power Stroke V8 engine and TorqShift HD transmission. Features robust construction, advanced technology, and versatile upfit options for demanding commercial applications.",
    horsepower: 330,
    features: ["Power Stroke V8", "TorqShift HD", "Robust Construction", "Advanced Technology", "Versatile Upfit", "Commercial Ready", "Superior Capability"],
    images: ["https://images.unsplash.com/photo-1522763866081-5be09778cd8b?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Mitsubishi",
    model: "Fuso FE180",
    year: 2023,
    mileage: 19200,
    price: 92000,
    condition: "certified",
    engine: "4P10 Turbodiesel",
    transmission: "Duonic 2.0",
    description: "The Mitsubishi Fuso FE180 combines efficiency and reliability with its 4P10 turbodiesel engine and Duonic 2.0 transmission. Features enhanced payload capacity, advanced safety systems, and excellent maneuverability for urban delivery.",
    horsepower: 161,
    features: ["4P10 Turbodiesel", "Duonic 2.0", "Enhanced Payload", "Advanced Safety", "Urban Optimized", "Excellent Maneuverability", "Efficiency Package"],
    images: ["https://images.unsplash.com/photo-1562876614-b8113b9aae14?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1565776877935-72d7a6dc421a?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "International",
    model: "CV515",
    year: 2024,
    mileage: 6500,
    price: 122000,
    condition: "new",
    engine: "Cummins L9",
    transmission: "Allison 3000",
    description: "The International CV515 delivers proven performance with its Cummins L9 engine and Allison 3000 transmission. Features advanced safety systems, comfortable operator environment, and excellent visibility for commercial applications.",
    horsepower: 300,
    features: ["Cummins L9 Engine", "Allison 3000", "Advanced Safety", "Comfortable Environment", "Excellent Visibility", "Commercial Ready", "Proven Performance"],
    images: ["https://images.unsplash.com/photo-1601312378427-822b2b41da35?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1586368555537-a8be1231d20f?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Volvo",
    model: "VNR 400",
    year: 2023,
    mileage: 24600,
    price: 125000,
    condition: "used",
    engine: "Volvo D11",
    transmission: "I-Shift",
    description: "The Volvo VNR 400 provides regional transport excellence with its D11 engine and I-Shift transmission. Features advanced safety systems, driver comfort technologies, and fuel-efficient design for regional distribution operations.",
    horsepower: 400,
    features: ["Volvo D11 Engine", "I-Shift", "Advanced Safety", "Driver Comfort", "Fuel Efficient", "Regional Optimized", "Distribution Ready"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Kenworth",
    model: "T270",
    year: 2024,
    mileage: 7800,
    price: 115000,
    condition: "new",
    engine: "PACCAR PX-7",
    transmission: "Allison 2500",
    description: "The Kenworth T270 combines performance and efficiency with its PACCAR PX-7 engine and Allison 2500 transmission. Features premium interior, advanced safety systems, and versatile configuration options for medium-duty applications.",
    horsepower: 300,
    features: ["PACCAR PX-7", "Allison 2500", "Premium Interior", "Advanced Safety", "Versatile Configuration", "Medium-Duty Optimized", "Performance Package"],
    images: ["https://images.unsplash.com/photo-1600661653561-629509216228?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Peterbilt",
    model: "325",
    year: 2023,
    mileage: 16800,
    price: 108000,
    condition: "certified",
    engine: "PACCAR PX-7",
    transmission: "automated-manual",
    description: "The Peterbilt 325 delivers versatile performance with its PACCAR PX-7 engine and automated manual transmission. Features classic Peterbilt styling, advanced technology, and reliable operation for diverse commercial applications.",
    horsepower: 300,
    features: ["PACCAR PX-7", "Automated Manual", "Classic Styling", "Advanced Technology", "Reliable Operation", "Versatile Performance", "Commercial Ready"],
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Mercedes-Benz",
    model: "Atego 1524",
    year: 2024,
    mileage: 4200,
    price: 132000,
    condition: "new",
    engine: "OM 936",
    transmission: "G210-9",
    description: "The Mercedes-Benz Atego 1524 offers superior performance with its OM 936 engine and G210-9 transmission. Features advanced safety systems, comfortable workspace, and proven reliability for demanding distribution operations.",
    horsepower: 240,
    features: ["OM 936 Engine", "G210-9 Transmission", "Advanced Safety", "Comfortable Workspace", "Proven Reliability", "Distribution Optimized", "Superior Performance"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d99?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Freightliner",
    model: "Cascadia P4",
    year: 2023,
    mileage: 31500,
    price: 98000,
    condition: "used",
    engine: "Detroit DD8",
    transmission: "DT12",
    description: "The Freightliner Cascadia P4 provides regional efficiency with its Detroit DD8 engine and DT12 transmission. Features aerodynamic design, advanced safety systems, and comfortable cab for regional and medium-duty applications.",
    horsepower: 350,
    features: ["Detroit DD8", "DT12 Transmission", "Aerodynamic Design", "Advanced Safety", "Comfortable Cab", "Regional Efficient", "Medium-Duty Ready"],
    images: ["https://images.unsplash.com/photo-1591768793355-74d04bb6608f?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1532976789241-e31cc4c7c16c?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Isuzu",
    model: "NPR-XD",
    year: 2024,
    mileage: 8900,
    price: 105000,
    condition: "new",
    engine: "Isuzu 5.2L",
    transmission: "automatic",
    description: "The Isuzu NPR-XD delivers enhanced capability with its 5.2L engine and automatic transmission. Features increased payload, improved safety systems, and excellent visibility for demanding medium-duty commercial applications.",
    horsepower: 215,
    features: ["5.2L Engine", "Automatic Transmission", "Increased Payload", "Improved Safety", "Excellent Visibility", "Enhanced Capability", "Commercial Optimized"],
    images: ["https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d99?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Hino",
    model: "258ALP",
    year: 2023,
    mileage: 26500,
    price: 85000,
    condition: "used",
    engine: "Hino J08E-VB",
    transmission: "automatic",
    description: "The Hino 258ALP provides reliable low-profile performance with its J08E-VB engine and automatic transmission. Features low cab height, enhanced maneuverability, and excellent fuel economy for specialized delivery applications.",
    horsepower: 230,
    features: ["Low Profile Design", "J08E-VB Engine", "Enhanced Maneuverability", "Fuel Economy", "Specialized Delivery", "Reliable Performance", "Low Cab Height"],
    images: ["https://images.unsplash.com/photo-1586368555537-a8be1231d20f?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Ford",
    model: "F-450",
    year: 2024,
    mileage: 2100,
    price: 89000,
    condition: "new",
    engine: "Power Stroke V8",
    transmission: "TorqShift HD",
    description: "The Ford F-450 Super Duty offers impressive capability with its Power Stroke V8 engine and TorqShift HD transmission. Features robust chassis, advanced towing technology, and versatile upfit options for commercial use.",
    horsepower: 475,
    features: ["Power Stroke V8", "TorqShift HD", "Robust Chassis", "Advanced Towing", "Versatile Upfit", "Commercial Use", "Impressive Capability"],
    images: ["https://images.unsplash.com/photo-1522763866081-5be09778cd8b?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Mitsubishi",
    model: "Fuso FG140",
    year: 2023,
    mileage: 14800,
    price: 78000,
    condition: "certified",
    engine: "4M50 Turbodiesel",
    transmission: "automatic",
    description: "The Mitsubishi Fuso FG140 provides efficient performance with its 4M50 turbodiesel engine and automatic transmission. Features compact design, excellent fuel economy, and reliable operation for light to medium-duty applications.",
    horsepower: 148,
    features: ["4M50 Turbodiesel", "Compact Design", "Fuel Economy", "Reliable Operation", "Light to Medium-Duty", "Efficient Performance", "Automatic Transmission"],
    images: ["https://images.unsplash.com/photo-1562876614-b8113b9aae14?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1565776877935-72d7a6dc421a?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "International",
    model: "HV515",
    year: 2024,
    mileage: 5600,
    price: 138000,
    condition: "new",
    engine: "Cummins L9",
    transmission: "Allison 4000",
    description: "The International HV515 delivers heavy-duty medium performance with its Cummins L9 engine and Allison 4000 transmission. Features robust construction, advanced safety systems, and excellent versatility for demanding applications.",
    horsepower: 350,
    features: ["Cummins L9", "Allison 4000", "Robust Construction", "Advanced Safety", "Excellent Versatility", "Heavy-Duty Medium", "Demanding Applications"],
    images: ["https://images.unsplash.com/photo-1601312378427-822b2b41da35?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1586368555537-a8be1231d20f?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Volvo",
    model: "VNR 300",
    year: 2023,
    mileage: 21800,
    price: 112000,
    condition: "used",
    engine: "Volvo D8K",
    transmission: "I-Shift",
    description: "The Volvo VNR 300 provides efficient regional transport with its D8K engine and I-Shift transmission. Features driver-centric design, advanced safety systems, and fuel-efficient operation for medium-duty commercial applications.",
    horsepower: 300,
    features: ["Volvo D8K", "I-Shift", "Driver-Centric Design", "Advanced Safety", "Fuel Efficient", "Regional Transport", "Commercial Applications"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1592805723127-004b174a1798?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Kenworth",
    model: "T170",
    year: 2024,
    mileage: 6200,
    price: 98000,
    condition: "new",
    engine: "PACCAR PX-7",
    transmission: "Allison 2000",
    description: "The Kenworth T170 combines efficiency and maneuverability with its PACCAR PX-7 engine and Allison 2000 transmission. Features compact design, excellent visibility, and proven reliability for urban and medium-duty applications.",
    horsepower: 260,
    features: ["PACCAR PX-7", "Allison 2000", "Compact Design", "Excellent Visibility", "Proven Reliability", "Urban Optimized", "Medium-Duty Ready"],
    images: ["https://images.unsplash.com/photo-1600661653561-629509216228?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Peterbilt",
    model: "348",
    year: 2023,
    mileage: 28900,
    price: 118000,
    condition: "certified",
    engine: "PACCAR PX-7",
    transmission: "automated-manual",
    description: "The Peterbilt 348 delivers versatile performance with its PACCAR PX-7 engine and automated manual transmission. Features rugged construction, advanced technology, and proven durability for medium to heavy-duty applications.",
    horsepower: 325,
    features: ["PACCAR PX-7", "Automated Manual", "Rugged Construction", "Advanced Technology", "Proven Durability", "Medium to Heavy-Duty", "Versatile Performance"],
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },
  {
    brand: "Mercedes-Benz",
    model: "Antos 1833",
    year: 2024,
    mileage: 3800,
    price: 145000,
    condition: "new",
    engine: "OM 936",
    transmission: "G211-12",
    description: "The Mercedes-Benz Antos 1833 provides construction-ready performance with its OM 936 engine and G211-12 transmission. Features robust design, advanced safety systems, and excellent maneuverability for construction and distribution applications.",
    horsepower: 330,
    features: ["OM 936 Engine", "G211-12 Transmission", "Construction Ready", "Robust Design", "Advanced Safety", "Excellent Maneuverability", "Distribution Optimized"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d99?w=800&h=500&fit=crop"],
    category: "medium-duty"
  },

  // Light-duty trucks (30 entries)
  {
    brand: "Ford",
    model: "F-550 Super Duty",
    year: 2024,
    mileage: 4500,
    price: 78000,
    condition: "new",
    engine: "Power Stroke V8",
    transmission: "automatic",
    description: "The Ford F-550 Super Duty features a 6.7L Power Stroke V8 turbo diesel engine with 475 hp and automatic transmission. Offers impressive towing and payload capabilities, making it ideal for commercial and construction applications.",
    horsepower: 475,
    features: ["Trailer Sway Control", "Tow/Haul Mode", "Power-Adjustable Pedals", "Rearview Camera", "SYNC 4", "FordPass Connect", "Pre-Collision Assist"],
    images: ["https://images.unsplash.com/photo-1579255982490-c8189860977e?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1543465077-db45d34b88a5?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Chevrolet",
    model: "Silverado 3500HD",
    year: 2023,
    mileage: 12800,
    price: 72000,
    condition: "used",
    engine: "Duramax 6.6L",
    transmission: "Allison 10-Speed",
    description: "The Chevrolet Silverado 3500HD is powered by a Duramax 6.6L turbo-diesel V8 engine with 445 hp and Allison 10-speed automatic transmission. Offers exceptional towing and hauling capabilities for commercial work and fleet applications.",
    horsepower: 445,
    features: ["Advanced Trailering System", "15 Camera Views", "Multi-Flex Tailgate", "Head-Up Display", "Trailer Brake Controller", "Digital Variable Steering Assist", "Auto-Locking Differential"],
    images: ["https://images.unsplash.com/photo-1568559598349-dbf322d0e338?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "RAM",
    model: "5500 Chassis Cab",
    year: 2022,
    mileage: 32500,
    price: 65000,
    condition: "certified",
    engine: "Cummins 6.7L",
    transmission: "AISIN 6-Speed",
    description: "The RAM 5500 Chassis Cab features a Cummins 6.7L turbo diesel engine with 360 hp and AISIN 6-speed automatic transmission. Offers exceptional capability, durability, and versatility for a wide range of commercial upfits and applications.",
    horsepower: 360,
    features: ["Trailer Sway Damping", "Auxiliary Switches", "Uconnect 5", "Active-Level Four-Corner Air Suspension", "360° Surround View Camera", "Lane Keep Assist", "Adaptive Cruise Control"],
    images: ["https://images.unsplash.com/photo-1558383817-c655269fb68f?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "GMC",
    model: "Sierra 3500HD",
    year: 2024,
    mileage: 8200,
    price: 76000,
    condition: "new",
    engine: "Duramax 6.6L",
    transmission: "Allison 10-Speed",
    description: "The GMC Sierra 3500HD is powered by a Duramax 6.6L turbo diesel engine with 445 hp and Allison 10-speed automatic transmission. Features ProGrade Trailering technology, MultiPro tailgate, and premium interior appointments for commercial applications.",
    horsepower: 445,
    features: ["ProGrade Trailering System", "MultiPro Tailgate", "Premium Interior", "15-inch Diagonal Head-Up Display", "High Definition Surround Vision", "Advanced Trailer System", "Denali Ultimate Package"],
    images: ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Isuzu",
    model: "NPR-HD",
    year: 2023,
    mileage: 18500,
    price: 58000,
    condition: "used",
    engine: "Isuzu 4HK1-TC",
    transmission: "automatic",
    description: "The Isuzu NPR-HD is equipped with a 4HK1-TC turbocharged diesel engine with 215 hp and automatic transmission. Offers excellent maneuverability, visibility, and reliability for urban delivery and service applications.",
    horsepower: 215,
    features: ["Keyless Entry", "Power Windows and Locks", "Air Conditioning", "Multi-Information Display", "Bluetooth Audio", "Trip Computer", "Cruise Control"],
    images: ["https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570058695872-9acb06dab0be?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Ford",
    model: "Transit-350 HD",
    year: 2024,
    mileage: 2100,
    price: 62000,
    condition: "new",
    engine: "Power Stroke V6",
    transmission: "SelectShift",
    description: "The Ford Transit-350 HD features a 3.2L Power Stroke V6 diesel engine with 185 hp and SelectShift automatic transmission. Designed for maximum cargo capacity and fuel efficiency with advanced connectivity and safety features.",
    horsepower: 185,
    features: ["SYNC 4", "Ford Co-Pilot360", "Intelligent 4WD", "Cargo Management System", "Rear View Camera", "LED Headlights", "Dual Zone Climate Control"],
    images: ["https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Nissan",
    model: "NV200 Compact Cargo",
    year: 2023,
    mileage: 24600,
    price: 35000,
    condition: "certified",
    engine: "2.0L 4-Cylinder",
    transmission: "CVT",
    description: "The Nissan NV200 Compact Cargo offers efficiency and versatility with its 2.0L 4-cylinder engine and CVT transmission. Perfect for urban delivery with excellent fuel economy, compact size, and surprising cargo capacity.",
    horsepower: 131,
    features: ["NissanConnect", "Bluetooth Connectivity", "Dual Sliding Doors", "Flat Load Floor", "Overhead Storage", "Mobile Office Package", "Rear Doors 180° Opening"],
    images: ["https://images.unsplash.com/photo-1562876614-b8113b9aae14?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d99?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Mercedes-Benz",
    model: "Sprinter 3500",
    year: 2024,
    mileage: 3800,
    price: 68000,
    condition: "new",
    engine: "OM 651 Turbo",
    transmission: "7G-TRONIC",
    description: "The Mercedes-Benz Sprinter 3500 features an OM 651 turbocharged engine with 188 hp and 7G-TRONIC automatic transmission. Offers exceptional cargo capacity, advanced safety features, and connectivity for commercial applications.",
    horsepower: 188,
    features: ["MBUX Multimedia System", "Active Brake Assist", "Crosswind Assist", "Lane Keeping Assist", "Blind Spot Assist", "Load Adaptive ESP", "High Roof Configuration"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Freightliner",
    model: "Sprinter 2500",
    year: 2023,
    mileage: 16200,
    price: 55000,
    condition: "used",
    engine: "Mercedes OM 651",
    transmission: "7G-TRONIC",
    description: "The Freightliner Sprinter 2500 combines Mercedes engineering with American market optimization. Features OM 651 engine, 7G-TRONIC transmission, and versatile cargo configuration for diverse commercial applications.",
    horsepower: 188,
    features: ["Crosswind Assist", "Active Brake Assist", "Attention Assist", "ECO Start/Stop", "Load Adaptive ESP", "Cargo Area LED Lighting", "Easy Entry System"],
    images: ["https://images.unsplash.com/photo-1591768793355-74d04bb6608f?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1586368555537-a8be1231d20f?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Chevrolet",
    model: "Express 3500",
    year: 2022,
    mileage: 29800,
    price: 48000,
    condition: "used",
    engine: "Vortec 6.0L V8",
    transmission: "6-Speed Automatic",
    description: "The Chevrolet Express 3500 is powered by a reliable Vortec 6.0L V8 engine with 342 hp and 6-speed automatic transmission. Offers excellent payload capacity, durability, and proven performance for commercial fleet applications.",
    horsepower: 342,
    features: ["StabiliTrak Electronic Stability Control", "Traction Control", "OnStar", "Remote Keyless Entry", "Power Door Locks", "Auxiliary Lighting", "Heavy-Duty Trailering Package"],
    images: ["https://images.unsplash.com/photo-1568559598349-dbf322d0e338?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570058695872-9acb06dab0be?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  // Additional 20 light-duty trucks
  {
    brand: "Ford",
    model: "F-350 Super Duty",
    year: 2024,
    mileage: 6800,
    price: 68000,
    condition: "new",
    engine: "Power Stroke V8",
    transmission: "TorqShift HD",
    description: "The Ford F-350 Super Duty delivers exceptional capability with its Power Stroke V8 engine and TorqShift HD transmission. Features advanced towing technology, comfortable interior, and robust construction for demanding commercial applications.",
    horsepower: 475,
    features: ["Power Stroke V8", "TorqShift HD", "Advanced Towing", "Comfortable Interior", "Robust Construction", "Commercial Ready", "Exceptional Capability"],
    images: ["https://images.unsplash.com/photo-1579255982490-c8189860977e?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1543465077-db45d34b88a5?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Chevrolet",
    model: "Silverado 2500HD",
    year: 2023,
    mileage: 18900,
    price: 58000,
    condition: "certified",
    engine: "Duramax 6.6L",
    transmission: "Allison 10-Speed",
    description: "The Chevrolet Silverado 2500HD provides heavy-duty performance with its Duramax 6.6L engine and Allison 10-speed transmission. Features advanced trailering systems, premium interior, and excellent capability for work and recreation.",
    horsepower: 445,
    features: ["Duramax 6.6L", "Allison 10-Speed", "Advanced Trailering", "Premium Interior", "Excellent Capability", "Work and Recreation", "Heavy-Duty Performance"],
    images: ["https://images.unsplash.com/photo-1568559598349-dbf322d0e338?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "RAM",
    model: "3500 Tradesman",
    year: 2024,
    mileage: 3200,
    price: 58000,
    condition: "new",
    engine: "Cummins 6.7L",
    transmission: "AISIN 6-Speed",
    description: "The RAM 3500 Tradesman offers commercial-grade capability with its Cummins 6.7L engine and AISIN 6-speed transmission. Features work-focused interior, advanced safety systems, and exceptional towing capacity for commercial operations.",
    horsepower: 370,
    features: ["Cummins 6.7L", "AISIN 6-Speed", "Work-Focused Interior", "Advanced Safety", "Exceptional Towing", "Commercial Operations", "Commercial-Grade Capability"],
    images: ["https://images.unsplash.com/photo-1558383817-c655269fb68f?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "GMC",
    model: "Sierra 2500HD",
    year: 2023,
    mileage: 22500,
    price: 55000,
    condition: "used",
    engine: "Duramax 6.6L",
    transmission: "Allison 10-Speed",
    description: "The GMC Sierra 2500HD combines power and refinement with its Duramax 6.6L engine and Allison 10-speed transmission. Features premium appointments, advanced technology, and professional capability for demanding applications.",
    horsepower: 445,
    features: ["Duramax 6.6L", "Allison 10-Speed", "Premium Appointments", "Advanced Technology", "Professional Capability", "Demanding Applications", "Power and Refinement"],
    images: ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Ford",
    model: "Transit-250",
    year: 2024,
    mileage: 4500,
    price: 52000,
    condition: "new",
    engine: "EcoBoost V6",
    transmission: "SelectShift",
    description: "The Ford Transit-250 offers versatile performance with its EcoBoost V6 engine and SelectShift transmission. Features flexible cargo configurations, advanced connectivity, and fuel-efficient operation for commercial delivery applications.",
    horsepower: 310,
    features: ["EcoBoost V6", "SelectShift", "Flexible Cargo", "Advanced Connectivity", "Fuel Efficient", "Commercial Delivery", "Versatile Performance"],
    images: ["https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Nissan",
    model: "NV1500",
    year: 2023,
    mileage: 16800,
    price: 42000,
    condition: "certified",
    engine: "5.6L V8",
    transmission: "7-Speed Automatic",
    description: "The Nissan NV1500 delivers reliable performance with its 5.6L V8 engine and 7-speed automatic transmission. Features spacious cargo area, comfortable cab, and proven durability for light commercial applications.",
    horsepower: 375,
    features: ["5.6L V8", "7-Speed Automatic", "Spacious Cargo", "Comfortable Cab", "Proven Durability", "Light Commercial", "Reliable Performance"],
    images: ["https://images.unsplash.com/photo-1562876614-b8113b9aae14?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d99?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Mercedes-Benz",
    model: "Metris",
    year: 2024,
    mileage: 5200,
    price: 48000,
    condition: "new",
    engine: "2.0L Turbo",
    transmission: "7G-TRONIC",
    description: "The Mercedes-Benz Metris provides European efficiency with its 2.0L turbo engine and 7G-TRONIC transmission. Features compact dimensions, premium interior, and excellent fuel economy for urban commercial applications.",
    horsepower: 208,
    features: ["2.0L Turbo", "7G-TRONIC", "Compact Dimensions", "Premium Interior", "Excellent Fuel Economy", "Urban Commercial", "European Efficiency"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Isuzu",
    model: "NPR",
    year: 2023,
    mileage: 21500,
    price: 52000,
    condition: "used",
    engine: "Isuzu 4HK1-TC",
    transmission: "automatic",
    description: "The Isuzu NPR offers dependable performance with its 4HK1-TC engine and automatic transmission. Features excellent visibility, tight turning radius, and proven reliability for urban delivery and service applications.",
    horsepower: 200,
    features: ["4HK1-TC Engine", "Automatic Transmission", "Excellent Visibility", "Tight Turning Radius", "Proven Reliability", "Urban Delivery", "Dependable Performance"],
    images: ["https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570058695872-9acb06dab0be?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Chevrolet",
    model: "Express 2500",
    year: 2024,
    mileage: 7200,
    price: 45000,
    condition: "new",
    engine: "Vortec 6.0L V8",
    transmission: "6-Speed Automatic",
    description: "The Chevrolet Express 2500 provides reliable commercial capability with its Vortec 6.0L V8 engine and 6-speed automatic transmission. Features spacious cargo area, comfortable seating, and proven durability for fleet applications.",
    horsepower: 342,
    features: ["Vortec 6.0L V8", "6-Speed Automatic", "Spacious Cargo", "Comfortable Seating", "Proven Durability", "Fleet Applications", "Reliable Commercial Capability"],
    images: ["https://images.unsplash.com/photo-1568559598349-dbf322d0e338?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570058695872-9acb06dab0be?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Ford",
    model: "E-350 Cutaway",
    year: 2023,
    mileage: 28500,
    price: 38000,
    condition: "used",
    engine: "Triton V8",
    transmission: "6-Speed Automatic",
    description: "The Ford E-350 Cutaway offers versatile upfit capability with its Triton V8 engine and 6-speed automatic transmission. Features robust chassis, excellent payload capacity, and proven reliability for specialized commercial applications.",
    horsepower: 305,
    features: ["Triton V8", "6-Speed Automatic", "Versatile Upfit", "Robust Chassis", "Excellent Payload", "Proven Reliability", "Specialized Commercial"],
    images: ["https://images.unsplash.com/photo-1579255982490-c8189860977e?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1543465077-db45d34b88a5?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "RAM",
    model: "ProMaster 3500",
    year: 2024,
    mileage: 3900,
    price: 55000,
    condition: "new",
    engine: "3.6L V6",
    transmission: "9-Speed Automatic",
    description: "The RAM ProMaster 3500 delivers maximum cargo capacity with its 3.6L V6 engine and 9-speed automatic transmission. Features low load floor, wide cargo doors, and excellent fuel economy for commercial delivery operations.",
    horsepower: 280,
    features: ["3.6L V6", "9-Speed Automatic", "Maximum Cargo Capacity", "Low Load Floor", "Wide Cargo Doors", "Excellent Fuel Economy", "Commercial Delivery"],
    images: ["https://images.unsplash.com/photo-1558383817-c655269fb68f?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Nissan",
    model: "NV3500",
    year: 2023,
    mileage: 19200,
    price: 46000,
    condition: "certified",
    engine: "5.6L V8",
    transmission: "7-Speed Automatic",
    description: "The Nissan NV3500 provides heavy-duty capability with its 5.6L V8 engine and 7-speed automatic transmission. Features high-roof configuration, excellent payload capacity, and comfortable driving experience for commercial applications.",
    horsepower: 375,
    features: ["5.6L V8", "7-Speed Automatic", "High-Roof Configuration", "Excellent Payload", "Comfortable Driving", "Commercial Applications", "Heavy-Duty Capability"],
    images: ["https://images.unsplash.com/photo-1562876614-b8113b9aae14?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d99?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Mercedes-Benz",
    model: "Sprinter 1500",
    year: 2024,
    mileage: 6500,
    price: 58000,
    condition: "new",
    engine: "OM 651 Turbo",
    transmission: "7G-TRONIC",
    description: "The Mercedes-Benz Sprinter 1500 combines efficiency and luxury with its OM 651 turbo engine and 7G-TRONIC transmission. Features premium interior, advanced safety systems, and excellent fuel economy for high-end commercial applications.",
    horsepower: 188,
    features: ["OM 651 Turbo", "7G-TRONIC", "Premium Interior", "Advanced Safety", "Excellent Fuel Economy", "High-End Commercial", "Efficiency and Luxury"],
    images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1566152960884-5a266668e5ed?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Ford",
    model: "Transit Connect",
    year: 2023,
    mileage: 25800,
    price: 32000,
    condition: "used",
    engine: "2.0L I4",
    transmission: "8-Speed Automatic",
    description: "The Ford Transit Connect offers compact efficiency with its 2.0L I4 engine and 8-speed automatic transmission. Features dual sliding doors, excellent fuel economy, and urban-friendly dimensions for small business applications.",
    horsepower: 162,
    features: ["2.0L I4", "8-Speed Automatic", "Dual Sliding Doors", "Excellent Fuel Economy", "Urban-Friendly", "Small Business", "Compact Efficiency"],
    images: ["https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570327920356-811d8dd4d58d?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Chevrolet",
    model: "City Express",
    year: 2022,
    mileage: 35600,
    price: 28000,
    condition: "used",
    engine: "2.0L I4",
    transmission: "CVT",
    description: "The Chevrolet City Express provides urban delivery capability with its 2.0L I4 engine and CVT transmission. Features compact design, excellent maneuverability, and efficient operation for city-based commercial applications.",
    horsepower: 131,
    features: ["2.0L I4", "CVT Transmission", "Compact Design", "Excellent Maneuverability", "Efficient Operation", "City-Based Commercial", "Urban Delivery Capability"],
    images: ["https://images.unsplash.com/photo-1568559598349-dbf322d0e338?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570058695872-9acb06dab0be?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "RAM",
    model: "ProMaster City",
    year: 2024,
    mileage: 8200,
    price: 35000,
    condition: "new",
    engine: "2.4L I4",
    transmission: "9-Speed Automatic",
    description: "The RAM ProMaster City delivers compact commercial capability with its 2.4L I4 engine and 9-speed automatic transmission. Features dual sliding doors, flat load floor, and excellent fuel economy for urban delivery applications.",
    horsepower: 178,
    features: ["2.4L I4", "9-Speed Automatic", "Dual Sliding Doors", "Flat Load Floor", "Excellent Fuel Economy", "Urban Delivery", "Compact Commercial Capability"],
    images: ["https://images.unsplash.com/photo-1558383817-c655269fb68f?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Isuzu",
    model: "NPR-EFI",
    year: 2023,
    mileage: 31500,
    price: 48000,
    condition: "certified",
    engine: "Isuzu 4HE1-XS",
    transmission: "automatic",
    description: "The Isuzu NPR-EFI provides reliable gas-powered performance with its 4HE1-XS engine and automatic transmission. Features low cab forward design, excellent visibility, and proven durability for light commercial applications.",
    horsepower: 205,
    features: ["4HE1-XS Engine", "Automatic Transmission", "Low Cab Forward", "Excellent Visibility", "Proven Durability", "Light Commercial", "Gas-Powered Performance"],
    images: ["https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1570058695872-9acb06dab0be?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Ford",
    model: "F-250 Super Duty",
    year: 2024,
    mileage: 9800,
    price: 62000,
    condition: "new",
    engine: "Power Stroke V8",
    transmission: "TorqShift HD",
    description: "The Ford F-250 Super Duty delivers robust capability with its Power Stroke V8 engine and TorqShift HD transmission. Features advanced towing technology, comfortable interior, and proven reliability for commercial and personal use.",
    horsepower: 475,
    features: ["Power Stroke V8", "TorqShift HD", "Advanced Towing", "Comfortable Interior", "Proven Reliability", "Commercial and Personal", "Robust Capability"],
    images: ["https://images.unsplash.com/photo-1579255982490-c8189860977e?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1543465077-db45d34b88a5?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "GMC",
    model: "Savana 3500",
    year: 2023,
    mileage: 24200,
    price: 42000,
    condition: "used",
    engine: "Vortec 6.0L V8",
    transmission: "6-Speed Automatic",
    description: "The GMC Savana 3500 provides commercial-grade capability with its Vortec 6.0L V8 engine and 6-speed automatic transmission. Features spacious cargo area, durable construction, and proven performance for fleet applications.",
    horsepower: 342,
    features: ["Vortec 6.0L V8", "6-Speed Automatic", "Spacious Cargo", "Durable Construction", "Proven Performance", "Fleet Applications", "Commercial-Grade Capability"],
    images: ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&h=500&fit=crop"],
    category: "light-duty"
  },
  {
    brand: "Nissan",
    model: "Titan XD",
    year: 2024,
    mileage: 12500,
    price: 58000,
    condition: "new",
    engine: "Cummins 5.0L V8",
    transmission: "7-Speed Automatic",
    description: "The Nissan Titan XD combines heavy-duty capability with light-duty convenience using its Cummins 5.0L V8 turbo diesel engine and 7-speed automatic transmission. Features premium interior, advanced technology, and exceptional towing capacity.",
    horsepower: 310,
    features: ["Cummins 5.0L V8", "7-Speed Automatic", "Premium Interior", "Advanced Technology", "Exceptional Towing", "Heavy-Duty Capability", "Light-Duty Convenience"],
    images: ["https://images.unsplash.com/photo-1562876614-b8113b9aae14?w=800&h=500&fit=crop", "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d99?w=800&h=500&fit=crop"],
    category: "light-duty"
  }
];

// Function to seed the database with predefined truck data
export const seedTruckDatabase = async () => {
  try {
    console.log("Starting to seed database with 90 realistic truck entries...");
    
    // Clear existing data first
    const { error: deleteError } = await supabase
      .from('trucks')
      .delete()
      .neq('id', '00000000-0000-0000-0000-000000000000'); // Delete all existing trucks
    
    if (deleteError && deleteError.code !== 'PGRST116') { // PGRST116 is "no rows found" which is fine
      console.error("Error clearing existing trucks:", deleteError);
    }
    
    // Insert each truck into the database
    for (const truck of truckSeedData) {
      const { error } = await supabase
        .from('trucks')
        .insert([truck]);
      
      if (error) {
        console.error("Error inserting truck:", error);
        toast({
          title: "Error",
          description: `Failed to add truck ${truck.brand} ${truck.model}: ${error.message}`,
          variant: "destructive",
        });
        return;
      }
    }
    
    toast({
      title: "Success",
      description: "Added 90 realistic truck entries to the database!",
      variant: "default",
    });
    
    console.log("Successfully seeded database with 90 trucks");
  } catch (error: any) {
    toast({
      title: "Error",
      description: `Failed to seed database: ${error.message}`,
      variant: "destructive",
    });
    console.error("Error seeding database:", error);
  }
};

// Auto-run the seeding function when this module is imported
seedTruckDatabase();
