import type { ChannelAdapter, ChannelResult, PublishingContext } from "../types.ts";

export const sitemapChannel: ChannelAdapter = {
  key: "sitemap",
  label: "Sitemap",
  supports: (e) =>
    e.event_type === "product.published" ||
    e.event_type === "product.updated" ||
    e.event_type === "product.unpublished",
  async publish(_ctx: PublishingContext): Promise<ChannelResult> {
    // Sitemap regeneration is handled at build time by scripts/generate-sitemap.ts.
    // In a live environment this adapter would call a rebuild webhook.
    return {
      status: "skipped",
      response: { note: "sitemap is regenerated by build script (scripts/generate-sitemap.ts)" },
    };
  },
};