REVOKE EXECUTE ON FUNCTION public.log_newsletter_campaign_audit() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_newsletter_entity_audit() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_publishing_event_insert() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_publishing_event_transition() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_products_auto_ready_for_social() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_refresh_social_hash_images() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_refresh_social_hash_products() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.claim_publishing_events(integer, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.refresh_product_social_hash(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.build_product_social_snapshot(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.compute_product_social_hash(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_meta_connection_status() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_meta_connection_status() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.claim_publishing_events(integer, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.refresh_product_social_hash(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.build_product_social_snapshot(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.compute_product_social_hash(uuid) TO service_role;