// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwwizgcjpytcutgkzfed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3d2l6Z2NqcHl0Y3V0Z2t6ZmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzIzNzcsImV4cCI6MjA2Mzk0ODM3N30.Oo9oSIf7plnPVapsZtlIBHsDyjewNootzJ0xa5cS8iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);