// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbguanjgjgardlznhxiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZ3VhbmpnamdhcmRsem5oeGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjUwMDYsImV4cCI6MjA2MTM0MTAwNn0.L8zWCBVs8h-XK85uJouB9E_WDuAdZkaWE95BeBBGQ0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);